import React, { createContext, useContext, useState } from 'react';

const translations = {
  hi: {
    home: 'होम',
    about: 'हमारे बारे में',
    courses: 'कोर्सेज',
    testimonials: 'समीक्षण',
    gallery: 'गैलरी',
    contact: 'संपर्क करें',
    welcome: 'अल्फा क्लासेज में आपका स्वागत है',
    tagline: 'गुणवत्ता शिक्षा के साथ उज्ज्वल भविष्य',
    admissionsOpen: 'एडमिशन ओपन 2026',
    mission: 'हमारा मिशन',
    missionText: 'छात्रों को गुणवत्ता शिक्षा प्रदान कर उनके भविष्य में उत्कृष्ट बनाना।',
    vision: 'हमारा दृष्टि',
    visionText: 'छात्रों को विषय में विशेषज्ञ बनाकर उनका ज्ञान बढ़ाना।',
    name: 'नाम',
    phone: 'फोन',
    message: 'संदेश',
    sendMessage: 'संदेश भेजें',
    email: 'ईमेल',
    call: 'कॉल करें',
    ourCourses: 'हमारे कोर्सेज',
    viewDetails: 'विवरण देखें',
    whatStudentsSay: 'छात्र क्या कहते हैं',
    studentOf: 'के छात्र',
    allRightsReserved: 'सर्वाधिकार सुरक्षित',
    followUs: 'हमें फॉलो करें',
    coachingInstitute: 'कोचिंग संस्थान',
    ourBranches: 'हमारी शाखाएं',
    admissionSubtitle: 'हमारे पाठ्यक्रम और सीमित बैच आकार के साथ उत्कृष्टता का अनुभव करें।',
    admissionNote1: 'आकांक्षा को उपलब्धि में बदलना।',
    admissionNote2: 'बैच समय, विषय मॉड्यूल और फीस संरचना के बारे में जानने के लिए हमारी बाद रोड गोदरी या इटिमहा शाखा पर आएं। जल्दी एडमिशन लेने वालों को बैच चयन में प्राथमिकता मिलती है।',
    enquireNow: 'अभी पूछें →',
    missionVisionTitle: 'हमारा मिशन और दृष्टि',
    missionVisionSubtitle: 'अनुशासित कोचिंग और व्यक्तिगत ध्यान से मजबूत शैक्षणिक नींव।',
    missionTitle: 'हमारा मिशन',
    missionDesc: 'बिहार के छात्रों को गणित और विज्ञान में मजबूत नींव देने और बोर्ड तथा प्रतियोगी परीक्षाओं में सफलता दिलाने के लिए अनुशासित, कॉन्सेप्ट-आधारित कोचिंग।',
    visionTitle: 'हमारा दृष्टि',
    visionDesc: 'अनुशासित कोचिंग, व्यक्तिगत ध्यान और परीक्षा-केंद्रित अभ्यास से बिहार के छात्रों के लिए मजबूत शैक्षणिक नींव बनाना।',
    keyPrograms: 'मुख्य प्रोग्राम',
    keyProgramsSubtitle: 'कक्षा 6वीं से 12वीं तक विशेषज्ञ कोचिंग और प्रतियोगी परीक्षा की तैयारी।',
    exploreAllCourses: 'सभी कोर्स देखें',
    studentSuccess: 'छात्र सफलता',
    studentSuccessSubtitle: 'अल्फा क्लासेज के साथ उत्कृष्ट प्रदर्शन करने वाले सैकड़ों छात्रों में शामिल हों।',
    academicPrograms: 'शैक्षणिक प्रोग्राम',
    academicProgramsSubtitle: 'स्कूली छात्रों और प्रतियोगी परीक्षा उम्मीदवारों के लिए उत्कृष्टता-संचालित कोचिंग बैच।',
    testimonialsSubtitle: 'छात्रों की ईमानदार राय और द अल्फा क्लासेज के साथ उनकी यात्रा।',
    gallerySubtitle: 'हमारी कक्षाओं, टेस्ट और छात्र गतिविधियों की झलक।',
    galleryNote: 'असली कक्षा और इवेंट फोटो से प्रतिस्थापित करें।',
    contactUs: 'संपर्क करें',
    contactSubtitle: 'एडमिशन, बैच विवरण या काउंसलिंग के लिए संपर्क करें।',
    instituteLocation: 'संस्थान स्थान (नमूना)',
    mapNote: 'मानचित्र संकेत के लिए है। अपनी शाखाओं का सटीक स्थान अपडेट करें।',
    meetFounder: 'संस्थापक से मिलें',
    meetFounderSubtitle: 'अनंद सर — अनुशासन, अनुभव और शैक्षणिक उत्कृष्टता के प्रति प्रतिबद्धता के साथ।',
    ourVision: 'हमारा दृष्टि',
    ourMission: 'हमारा मिशन',
    branches: 'शाखाएं',
    connectWithUs: 'हमसे जुड़ें',
    quickLinks: 'त्वरित लिंक',
    coursesLink: 'कोर्सेज',
    testimonialsLink: 'समीक्षण',
    contactLink: 'संपर्क',
    nameRequired: 'नाम आवश्यक है।',
    phoneRequired: 'फोन नंबर आवश्यक है।',
    phoneInvalid: '10 अंकों का मोबाइल नंबर दर्ज करें।',
    messageRequired: 'संदेश आवश्यक है।',
    yourName: 'आपका नाम',
    yourPhone: 'आपका फोन नंबर',
    yourMessage: 'आपका संदेश',
    thankYouMessage: 'संपर्क करने के लिए धन्यवाद। हम जल्द ही संपर्क करेंगे।',
    emailLabel: 'ईमेल',
    callLabel: 'कॉल करें',
    // Founder
    founderTitle: 'संस्थापक और शैक्षणिक मेंटर',
    founderIntro: 'सेमी-अर्बन इलाकों में छात्रों की चुनौतियों को समझते हुए, हमारे संस्थापक ने बिहार के रोहतास के छात्रों के लिए संरचित, कॉन्सेप्ट-आधारित कोचिंग लाने के लिए द अल्फा क्लासेज की स्थापना की।',
    founderBio1: 'अल्फा क्लासेज में हम मानते हैं कि सही रणनीति, अनुशासन और कॉन्सेप्ट क्लैरिटी के साथ हर छात्र उत्कृष्ट परिणाम हासिल कर सकता है। हमारी कक्षा संस्कृति रटने के बजाय समझ पर केंद्रित है।',
    founderBio2: 'संस्थापक व्यक्तिगत रूप से शैक्षणिक योजनाएं, टेस्ट संरचना और संस्थान में इस्तेमाल होने वाले डाउट-सॉल्विंग फ्रेमवर्क डिज़ाइन करते हैं। अभिभावकों के साथ नियमित बातचीत और प्रदर्शन ट्रैकिंग से हर बच्चे को व्यक्तिगत ध्यान मिलता है।',
    founderBio3: 'वर्षों से, उनके मार्गदर्शन में छात्रों ने स्कूल परीक्षाओं में अच्छा प्रदर्शन किया है और विशेष रूप से गणित और विज्ञान में प्रतियोगी परीक्षाओं के लिए मजबूत आधार बनाया है।',
    founderVision: 'अनुशासित कोचिंग, व्यक्तिगत ध्यान और परीक्षा-केंद्रित अभ्यास के माध्यम से बिहार के छात्रों के लिए मजबूत शैक्षणिक नींव बनाना।',
    founderMission: 'एक विश्वसनीय पड़ोस कोचिंग संस्थान बनाना जहां अभिभावक भरोसा कर सकें कि उनके बच्चे को संरचित मार्गदर्शन, नियमित फीडबैक और शैक्षणिक सफलता के लिए स्पष्ट रोडमैप मिल रहा है।',
    // Courses (by id)
    'course_cls-8-10_title': 'कक्षा 8 – 10 (फाउंडेशन बैच)',
    'course_cls-8-10_description': 'नियमित टेस्ट, असाइनमेंट और डाउट सेशन के साथ गणित और विज्ञान में मजबूत नींव।',
    'course_cls-8-10_h1': 'एनसीईआरटी-केंद्रित पढ़ाई',
    'course_cls-8-10_h2': 'साप्ताहिक चैप्टर टेस्ट',
    'course_cls-8-10_h3': 'कॉन्सेप्ट रिवीजन शीट',
    'course_cls-11-12-sci_title': 'कक्षा 11 – 12 (विज्ञान)',
    'course_cls-11-12-sci_description': 'परीक्षा-उन्मुख अभ्यास के साथ भौतिकी, रसायन और गणित पर फोकस।',
    'course_cls-11-12-sci_h1': 'टॉपिक-वाइज नोट्स',
    'course_cls-11-12-sci_h2': 'न्यूमेरिकल प्रैक्टिस',
    'course_cls-11-12-sci_h3': 'बोर्ड + प्रतियोगी ओरिएंटेशन',
    'course_competitive_title': 'प्रतियोगी परीक्षा सहायता',
    'course_competitive_description': 'प्रॉब्लम सॉल्विंग और टाइम मैनेजमेंट पर जोर के साथ प्रतियोगी परीक्षाओं की शुरुआती मार्गदर्शन।',
    'course_competitive_h1': 'ऑब्जेक्टिव पैटर्न प्रैक्टिस',
    'course_competitive_h2': 'स्पीड और एक्युरेसी सुधार',
    'course_competitive_h3': 'डाउट-क्लीयरिंग सेशन',
    // Testimonials
    'testimonial_t1_message': 'अल्फा क्लासेज ने मुझे गणित को बहुत सरल और स्पष्ट तरीके से समझने में मदद की। नियमित टेस्ट और फीडबैक ने बोर्ड से पहले मेरा आत्मविश्वास बढ़ाया।',
    'testimonial_t1_course': 'कक्षा 10 फाउंडेशन बैच',
    'testimonial_t2_message': 'कॉन्सेप्ट-वाइज पढ़ाई और नियमित डाउट सेशन ने बड़ा फर्क किया। सही मार्गदर्शन में मैं समय पर पूरी सिलेबस रिवाइज कर सका।',
    'testimonial_t2_course': 'कक्षा 12 विज्ञान',
    'testimonial_t3_message': 'संस्थान पहले बेसिक्स पर फोकस करता है फिर उच्च स्तर के प्रश्नों पर जाता है। इससे मुश्किल सवालों से डर नहीं लगा।',
    'testimonial_t3_course': 'प्रतियोगी सहायता',
    // Footer mission (long)
    missionFull: 'बिहार के छात्रों को गणित और विज्ञान में मजबूत नींव देने और बोर्ड तथा प्रतियोगी परीक्षाओं में सफलता के लिए अनुशासित, कॉन्सेप्ट-आधारित कोचिंग।',
    admissionOpenText: 'अकादमिक सत्र 2025-26 के लिए एडमिशन खुले हैं',
  },
  en: {
    home: 'Home',
    about: 'About',
    courses: 'Courses',
    testimonials: 'Testimonials',
    gallery: 'Gallery',
    contact: 'Contact',
    welcome: 'Welcome to ALPHA CLASSES',
    tagline: 'Quality education with excellent subject matter',
    admissionsOpen: 'Admissions Open 2026',
    mission: 'Our Mission',
    missionText: 'To provide quality education to students and make them excellent in their subjects.',
    vision: 'Our Vision',
    visionText: 'To make students experts in their subjects and enhance their knowledge.',
    name: 'Name',
    phone: 'Phone',
    message: 'Message',
    sendMessage: 'Send Message',
    email: 'Email',
    call: 'Call',
    ourCourses: 'Our Courses',
    viewDetails: 'View Details',
    whatStudentsSay: 'What Students Say',
    studentOf: 'Student of',
    allRightsReserved: 'All Rights Reserved',
    followUs: 'Follow Us',
    coachingInstitute: 'Coaching Institute',
    ourBranches: 'Our Branches',
    admissionSubtitle: 'Experience excellence with our structured curriculum and focused batch sizes.',
    admissionNote1: 'Transforming aspiration into achievement.',
    admissionNote2: 'Visit our Bad Road Godari or Itimha branches to learn about our batch timings, tailored subject modules, and fee structures. Early admissions receive priority for batch selection.',
    enquireNow: 'Enquire Now →',
    missionVisionTitle: 'Our Mission & Vision',
    missionVisionSubtitle: 'Building strong academic foundations through disciplined coaching and personalized attention.',
    missionTitle: 'Our Mission',
    missionDesc: 'To provide disciplined, concept-driven coaching that helps students from Bihar build a strong foundation in Mathematics and Science and succeed in board as well as competitive examinations.',
    visionTitle: 'Our Vision',
    visionDesc: 'To build a strong academic foundation for students of Bihar through disciplined coaching, personalised attention, and exam-focused practice.',
    keyPrograms: 'Key Programs',
    keyProgramsSubtitle: 'Expert coaching for Class 6th to 12th and specialized competitive exam preparation.',
    exploreAllCourses: 'Explore All Courses',
    studentSuccess: 'Student Success',
    studentSuccessSubtitle: 'Join hundreds of successful students who have excelled with ALPHA CLASSES.',
    academicPrograms: 'Academic Programs',
    academicProgramsSubtitle: 'Excellence-driven coaching batches for school students and competitive exam aspirants.',
    testimonialsSubtitle: 'Honest feedback from students and their journey with The ALPHA CLASSES.',
    gallerySubtitle: 'A glimpse of our classrooms, tests and student interactions.',
    galleryNote: 'Replace with actual classroom and event photos from The ALPHA CLASSES.',
    contactUs: 'Contact Us',
    contactSubtitle: 'Reach out for admissions, batch details or counselling.',
    instituteLocation: 'Institute Location (Sample)',
    mapNote: 'Map location is indicative. Update with the exact location of your branches.',
    meetFounder: 'Meet our Founder',
    meetFounderSubtitle: 'Anand Sir — Leading with discipline, experience, and a commitment to academic excellence.',
    ourVision: 'Our Vision',
    ourMission: 'Our Mission',
    branches: 'Branches',
    connectWithUs: 'Connect With Us',
    quickLinks: 'Quick Links',
    coursesLink: 'Courses',
    testimonialsLink: 'Testimonials',
    contactLink: 'Contact',
    nameRequired: 'Name is required.',
    phoneRequired: 'Phone number is required.',
    phoneInvalid: 'Enter a 10-digit mobile number.',
    messageRequired: 'Message is required.',
    yourName: 'Your Name',
    yourPhone: 'Your Phone Number',
    yourMessage: 'Your Message',
    thankYouMessage: 'Thank you for contacting us. We will reach out soon.',
    emailLabel: 'Email',
    callLabel: 'Call',
    founderTitle: 'Founder & Academic Mentor',
    founderIntro: 'With years of focused teaching experience and a deep understanding of the challenges faced by students in semi-urban areas, our founder established The ALPHA CLASSES to bring structured, concept-based coaching to students of Rohtas, Bihar.',
    founderBio1: 'At The ALPHA CLASSES, we believe that every student can achieve excellent results when guided with the right strategy, discipline, and conceptual clarity. Our classroom culture focuses on understanding rather than memorisation.',
    founderBio2: 'The founder personally designs the academic plans, test structures, and doubt-solving frameworks followed at the institute. Regular interaction with parents and consistent performance tracking ensures that every child receives individual attention.',
    founderBio3: 'Over the years, students mentored under him have performed strongly in school examinations and built a solid base for competitive exams, especially in Mathematics and Science.',
    founderVision: 'To build a strong academic foundation for students of Bihar through disciplined coaching, personalised attention, and exam-focused practice.',
    founderMission: 'To create a reliable neighbourhood coaching institute where parents can trust that their child is receiving structured guidance, regular feedback, and a clear roadmap for academic success.',
    'course_cls-8-10_title': 'Class 8 – 10 (Foundation Batch)',
    'course_cls-8-10_description': 'Strong foundation in Mathematics and Science with regular tests, assignments and doubt sessions.',
    'course_cls-8-10_h1': 'NCERT-focused teaching',
    'course_cls-8-10_h2': 'Weekly chapter tests',
    'course_cls-8-10_h3': 'Concept revision sheets',
    'course_cls-11-12-sci_title': 'Class 11 – 12 (Science)',
    'course_cls-11-12-sci_description': 'Focused coaching for Physics, Chemistry and Mathematics with exam-oriented practice.',
    'course_cls-11-12-sci_h1': 'Topic-wise notes',
    'course_cls-11-12-sci_h2': 'Numerical problem practice',
    'course_cls-11-12-sci_h3': 'Board + competitive orientation',
    'course_competitive_title': 'Competitive Exam Support',
    'course_competitive_description': 'Early guidance for competitive exams with emphasis on problem solving and time management.',
    'course_competitive_h1': 'Objective pattern practice',
    'course_competitive_h2': 'Speed and accuracy improvement',
    'course_competitive_h3': 'Doubt-clearing clinics',
    'testimonial_t1_message': 'The ALPHA CLASSES helped me understand Mathematics in a very simple and clear way. Regular tests and feedback improved my confidence before boards.',
    'testimonial_t1_course': 'Class 10 Foundation Batch',
    'testimonial_t2_message': 'Concept-wise teaching and regular doubt sessions made a big difference. I could revise the whole syllabus in time with proper guidance.',
    'testimonial_t2_course': 'Class 12 Science',
    'testimonial_t3_message': 'The institute focuses on basics first and then moves to higher level problems. This helped me not to fear difficult questions.',
    'testimonial_t3_course': 'Competitive Support',
    missionFull: 'To provide disciplined, concept-driven coaching that helps students from Bihar build a strong foundation in Mathematics and Science and succeed in board as well as competitive examinations.',
    admissionOpenText: 'Admissions Open for Academic Session 2025-26',
  }
};

const LanguageContext = createContext();

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  // Hindi is default; users can switch to English via the language toggle
  const [language, setLanguage] = useState('hi');
  
  const t = (key) => {
    return translations[language]?.[key] ?? translations.en[key] ?? key;
  };
  
  const toggleLanguage = () => {
    setLanguage(prev => prev === 'hi' ? 'en' : 'hi');
  };
  
  return (
    <LanguageContext.Provider value={{ language, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
